### ISSUE TITLE
Another login fail

### ISSUE THREAD

**Issue by ThatSmart** [embee8/homebridge-panasonic-ac-platform#48]
Same issue as previous, doesn't help changing to v1.16.0

Homebridge Panasonic AC Platform] Login failed. The Comfort Cloud server might be experiencing issues at the moment. Homebridge will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Homebridge when you change your config, as it will probably not have an effect on its own. If the error still persists, please report to https://github.com/embee8/homebridge-panasonic-ac-platform/issues.

**Comment by embee8** [comment]
Can you provide logs with timestamps which could help us figure out the order of events?

**Comment by JurgenLB** [comment]
Have you accepted the 'new' privacy declaration in the app ?
This is something the homebridge-panasonic-ac-platform can not do for you.

**Comment by JurgenLB** [comment]
today I notice another 'Login Fail' in my Log;
`[22/01/2023, 20:01:43] [Homebridge Panasonic AC Platform] Attempting to log into Comfort Cloud.
[22/01/2023, 20:01:44] [Homebridge Panasonic AC Platform] Login failed. Skipping device discovery.
[22/01/2023, 20:01:44] [Homebridge Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment. Homebridge will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Homebridge when you change your config. If the error still persists, please report it at https://github.com/embee8/homebridge-panasonic-ac-platform/issues.
[22/01/2023, 20:01:44] [Homebridge Panasonic AC Platform] Attempting to log into Comfort Cloud.
[22/01/2023, 20:01:44] [Homebridge Panasonic AC Platform] Attempting to log into Comfort Cloud.
[22/01/2023, 20:01:45] [Homebridge Panasonic AC Platform] Login failed. Skipping device discovery.
[22/01/2023, 20:01:45] [Homebridge Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment. Homebridge will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Homebridge when you change your config. If the error still persists, please report it at https://github.com/embee8/homebridge-panasonic-ac-platform/issues.
[22/01/2023, 20:01:45] [Homebridge Panasonic AC Platform] Login failed. Skipping device discovery.
[22/01/2023, 20:01:45] [Homebridge Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment. Homebridge will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Homebridge when you change your config. If the error still persists, please report it at https://github.com/embee8/homebridge-panasonic-ac-platform/issues.
[22/01/2023, 20:01:45] [Homebridge Panasonic AC Platform] Attempting to log into Comfort Cloud.
[22/01/2023, 20:01:46] [Homebridge Panasonic AC Platform] Login failed. Skipping device discovery.
[22/01/2023, 20:01:46] [Homebridge Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment. Homebridge will try to log in again in 360 seconds. If the issue persists, make sure you configured the correct email and password and run the latest version of the plugin. Restart Homebridge when you change your config. If the error still persists, please report it at https://github.com/embee8/homebridge-panasonic-ac-platform/issues.`

I checkt te APP and there is another Privacy notice;
![Privacy Notice](https://user-images.githubusercontent.com/77586573/213934922-5d4a5763-bcc2-49b2-a51e-e6a3e8c5c57c.png)

What can we check before accepting? so we can have more information about this?

**Comment by JurgenLB** [comment]
after putting 'Debug-mode On' in the setting and restarting;
`"message": "Request failed with status code 429",
  "name": "Error",
  "stack": "Error: Request failed with status code 429\n    at createError (/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "headers": {
      "Accept": "application/json; charset=UTF-8",
      "Content-Type": "application/json",
      "User-Agent": "G-RAC",
      "X-APP-TYPE": "0",
      "X-APP-VERSION": "1.17.0",
      "Content-Length": 83
    },
    "method": "post",
    "url": "https://accsmart.panasonic.com/auth/login",
    "data": "{\"loginId\":\"****",\"language\":\"0\",\"password\":\"****"}"
  },
  "status": 429
}`

**Comment by JurgenLB** [comment]
Also I notice the statement is "Homebridge will try to log in again in 360 seconds." But I see it filling up my log multiple time per minute .

**Comment by mkz212** [comment]
@JurgenLB 

If You want to fix this, probably the simplest way is go to Homebridge Terminal and type:

sudo nano /usr/local/lib/node_modules/homebridge-panasonic-ac-platform/dist/platform.js

Here change setInterval to setTimeout and save and restart homebridge.

Or You can edit this file via FTP.

**Comment by JurgenLB** [comment]
@mkz212 yes for the interval this seems te be better. But for the "Privacy Notice" there is some work to do.
Also I install Homebridge with the UI and hb-service, so my install location is not the same;
`/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/dist/platform.js`
I'm on Raspbian Bulleye
